[build]
  publish = ".next"
  command = "npm run build:netlify"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_FLAGS = "--production=false"
  NEXT_TELEMETRY_DISABLED = "1"

# Configurações para Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache para assets estáticos
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache para imagens
[[headers]]
  for = "/_next/image/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configurações de função para API routes
[functions]
  directory = "netlify/functions"

# Configurações específicas para Next.js no Netlify
[context.production]
  command = "npm run build:netlify"
  [context.production.environment]
    NODE_ENV = "production"
  
[context.deploy-preview]
  command = "npm run build:netlify"
  [context.deploy-preview.environment]
    NODE_ENV = "production"

[context.branch-deploy]
  command = "npm run build:netlify"
  [context.branch-deploy.environment]
    NODE_ENV = "production"

# Redirecionamento para Next.js static assets
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

# Redirecionamento geral para SPA (deve ser o último)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200